#!/usr/bin/env python
"""
Generate config/command_synopses.cfg from // Synopsis: comments in all
textcmd .src files (both scripts/textcmd/ and pkg/.../textcmd|commands/).

Run from the POL root directory:
    python _gen_command_synopses_cfg.py
"""

import os
import glob
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR) if os.path.basename(SCRIPT_DIR).lower() == "pythonscripts" else SCRIPT_DIR
OUT = os.path.join(ROOT, "config", "command_synopses.cfg")

SYNOPSIS_RE = re.compile(r"^//\s*Synopsis:\s*(.+)", re.IGNORECASE)

# Map lowercase dir name to (display label, actual POL cmdlevel number).
# Cmdlevels are assigned by position in config/cmds.cfg (0-indexed):
# Player=0, Coun=1, Seer=2, GM=3, Admin=4, Test=5
LEVEL_MAP = {
    "player": ("Player", 0),
    "coun": ("Counselor", 1),
    "seer": ("Seer", 2),
    "gm": ("Game Master", 3),
    "admin": ("Administrator", 4),
    "test": ("Developer", 5),
}


def extract_synopsis(filepath):
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            first = f.readline()
        m = SYNOPSIS_RE.match(first.strip())
        return m.group(1).strip() if m else None
    except Exception:
        return None


def collect():
    """Return dict: command_name_lower -> (original_name, synopsis, level_label, cmdlevel).
    First occurrence wins -- scripts/textcmd/ is scanned before pkg/."""
    synopses = {}

    sources = (
        [(os.path.join(ROOT, "scripts", "textcmd", lvl, "*.src"), lvl) for lvl in LEVEL_MAP]
        + [
            (os.path.join(ROOT, "pkg", "**", sub, lvl, "*.src"), lvl)
            for sub in ("textcmd", "commands")
            for lvl in LEVEL_MAP
        ]
    )

    for pattern, level_dir in sources:
        label, cmdlvl = LEVEL_MAP[level_dir]
        for path in sorted(glob.glob(pattern, recursive=True)):
            name = os.path.splitext(os.path.basename(path))[0]
            key = name.lower()
            if key not in synopses:
                synopsis = extract_synopsis(path)
                if synopsis:
                    synopses[key] = (name, synopsis, label, cmdlvl)

    return synopses


def write_cfg(synopses):
    lines = [
        "// Auto-generated by _gen_command_synopses_cfg.py -- do not edit by hand",
        "// Re-run the script after adding/changing // Synopsis: lines in .src files",
        "",
    ]
    for key in sorted(synopses.keys()):
        original, synopsis, level, cmdlevel = synopses[key]
        synopsis = synopsis.replace("{", "(").replace("}", ")")
        lines.append(f"Command {original}")
        lines.append("{")
        lines.append(f"\tSynopsis\t{synopsis}")
        lines.append(f"\tLevel\t\t{level}")
        lines.append(f"\tCmdLevel\t{cmdlevel}")
        lines.append("}")
        lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    return len(synopses)


if __name__ == "__main__":
    synopses = collect()
    count = write_cfg(synopses)
    print(f"Written {count} command synopses to {OUT}")
