#!/usr/bin/env python
"""
Generate pkg/opt/alryc/config/animatedgraphics.cfg from config/tiles.cfg.

The script scans tile blocks, selects tiles where UoFlags contains the
animated bit (0x01000000), then writes groups of N tiles (default 50)
using this format:

Group 1
{
    Tile 0x21c
    Tile 0x3ae
    ...
}

Run from repository root:
    python pythonscripts/_gen_alryc_animatedgraphics_cfg.py

Optional arguments:
    --input config/tiles.cfg
    --output pkg/opt/alryc/config/animatedgraphics.cfg
    --group-size 50
    --flag 0x01000000
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent if SCRIPT_DIR.name.lower() == "pythonscripts" else SCRIPT_DIR

DEFAULT_INPUT = ROOT / "config" / "tiles.cfg"
DEFAULT_OUTPUT = ROOT / "pkg" / "opt" / "alryc" / "config" / "animatedgraphics.cfg"

TILE_RE = re.compile(r"^\s*tile\s+(0x[0-9a-fA-F]+)\s*$")
UOFLAGS_RE = re.compile(r"^\s*UoFlags\s+([^\s]+)\s*$")
BLOCK_END_RE = re.compile(r"^\s*}\s*$")


def parse_int(value: str) -> int:
    return int(value, 0)


def collect_animated_tiles(tiles_cfg: Path, flag: int) -> list[int]:
    tiles: list[int] = []
    current_tile: int | None = None
    current_has_flag = False

    with tiles_cfg.open("r", encoding="utf-8", errors="replace") as file_handle:
        for raw in file_handle:
            line = raw.rstrip("\r\n")

            m_tile = TILE_RE.match(line)
            if m_tile:
                current_tile = parse_int(m_tile.group(1))
                current_has_flag = False
                continue

            if current_tile is None:
                continue

            m_flags = UOFLAGS_RE.match(line)
            if m_flags:
                try:
                    flags = parse_int(m_flags.group(1))
                except ValueError:
                    flags = 0
                if flags & flag:
                    current_has_flag = True
                continue

            if BLOCK_END_RE.match(line):
                if current_has_flag:
                    tiles.append(current_tile)
                current_tile = None
                current_has_flag = False

    return tiles


def write_grouped_cfg(output_cfg: Path, tiles: list[int], group_size: int) -> int:
    output_cfg.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("// Auto-generated by _gen_alryc_animatedgraphics_cfg.py")
    lines.append("// Do not edit by hand. Re-run generator after tiles.cfg changes.")
    lines.append("")

    group_count = 0
    for start in range(0, len(tiles), group_size):
        group_count += 1
        chunk = tiles[start : start + group_size]
        lines.append(f"Group {group_count}")
        lines.append("{")
        for tile in chunk:
            lines.append(f"    Tile {hex(tile)}")
        lines.append("}")
        lines.append("")

    output_cfg.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return group_count


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate alryc animated graphics group cfg from tiles.cfg")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Path to tiles.cfg")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Path to animatedgraphics.cfg")
    parser.add_argument("--group-size", type=int, default=50, help="Tiles per group")
    parser.add_argument("--flag", default="0x01000000", help="UoFlags bit mask for animated tiles")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"ERROR: input file not found: {input_path}")
        return 1

    if args.group_size <= 0:
        print("ERROR: --group-size must be > 0")
        return 1

    try:
        flag = parse_int(str(args.flag))
    except ValueError:
        print(f"ERROR: invalid --flag value: {args.flag}")
        return 1

    tiles = collect_animated_tiles(input_path, flag)
    group_count = write_grouped_cfg(output_path, tiles, args.group_size)

    rel_input = os.path.relpath(input_path, ROOT)
    rel_output = os.path.relpath(output_path, ROOT)
    print(f"Input: {rel_input}")
    print(f"Output: {rel_output}")
    print(f"Animated tiles found: {len(tiles)}")
    print(f"Groups written: {group_count}")
    print(f"Group size: {args.group_size}")
    print(f"Flag: {hex(flag)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())