from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
AREAS_PATH = ROOT / "pkg" / "opt" / "areas" / "areas.cfg"
REGIONS_PATH = ROOT / "regions" / "regions.cfg"
OUTPUT_PATH = ROOT / "config" / "golocs_by_id.cfg"


AREA_SECTION_RE = re.compile(r"^\s*Areas\s+(\S+)\s*$", re.IGNORECASE)
AREA_LINE_RE = re.compile(
    r"^\s*Area\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+id=(\S+)\s+(.+?)\s*$",
    re.IGNORECASE,
)
REGION_HEADER_RE = re.compile(r"^\s*Region\s+(.+?)\s*$", re.IGNORECASE)


def parse_areas(path: Path) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    current_realm: str | None = None

    for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue

        section_match = AREA_SECTION_RE.match(line)
        if section_match:
            current_realm = section_match.group(1)
            continue

        area_match = AREA_LINE_RE.match(raw_line)
        if not area_match or current_realm is None:
            continue

        min_x, max_x, min_y, max_y, area_id, name = area_match.groups()
        entries.append(
            {
                "realm": current_realm,
                "id": area_id,
                "name": name.strip(),
                "range": f"{min_x} {min_y} {max_x} {max_y}",
            }
        )

    return entries


def parse_regions(path: Path) -> dict[str, dict[str, str]]:
    regions_by_id: dict[str, dict[str, str]] = {}
    pending_region_name: str | None = None
    current_region: dict[str, str] | None = None

    for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("//"):
            continue

        header_match = REGION_HEADER_RE.match(raw_line)
        if header_match and current_region is None:
            pending_region_name = header_match.group(1).strip()
            continue

        if stripped == "{":
            current_region = {}
            if pending_region_name:
                current_region["HeaderName"] = pending_region_name
            pending_region_name = None
            continue

        if stripped == "}":
            if current_region:
                region_id = current_region.get("Id", "").strip()
                if region_id:
                    regions_by_id[region_id.lower()] = current_region
            current_region = None
            pending_region_name = None
            continue

        if current_region is None:
            continue

        parts = stripped.split(None, 1)
        key = parts[0]
        value = parts[1].strip() if len(parts) > 1 else ""
        current_region[key] = value

    return regions_by_id


def build_output(areas: list[dict[str, str]], regions_by_id: dict[str, dict[str, str]]) -> str:
    lines = [
        "# Generated by pythonscripts/generate_golocs_by_id.py",
        "# Source: pkg/opt/areas/areas.cfg + regions/regions.cfg",
        "",
    ]

    for area in areas:
        region = regions_by_id.get(area["id"].lower(), {})
        name = region.get("Name", "").strip() or area["name"]
        region_id = region.get("Id", "").strip() or area["id"]
        region_type = region.get("Type", "").strip() or "None"
        realm = region.get("Realm", "").strip() or area["realm"]

        lines.append(f"GoLocEntry {region_id}")
        lines.append("{")
        lines.append(f"\tRealm\t{realm}")
        lines.append(f"\tName\t{name}")
        lines.append(f"\tId\t{region_id}")
        lines.append(f"\tType\t{region_type}")
        lines.append(f"\tRange\t{area['range']}")

        goloc = region.get("GoLoc", "").strip()
        if goloc:
            lines.append(f"\tGoLoc\t{goloc}")

        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    areas = parse_areas(AREAS_PATH)
    regions_by_id = parse_regions(REGIONS_PATH)
    output = build_output(areas, regions_by_id)
    OUTPUT_PATH.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {len(areas)} entries to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()